[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

# Canonicalize www -> apex (optional, if you use this domain)
[[redirects]]
  from = "https://www.novatradeapp.com/*"
  to   = "https://novatradeapp.com/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Scheduled function
[functions."applyMoonPlan"]
  schedule = "0 3 * * *"
