[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

# Canonicalize www -> apex
[[redirects]]
  from = "https://www.novatradeapp.com/*"
  to   = "https://novatradeapp.com/:splat"
  status = 301
  force = true

# 🚧 Maintenance mode redirect
[[redirects]]
  from = "/*"
  to   = "/maintenance.html"
  status = 200

# SPA fallback (⚠️ disabled while maintenance is active)
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200

# Scheduled function
[functions."applyMoonPlan"]
  schedule = "0 3 * * *"
